services:
  payroc.server:
    image: ${DOCKER_REGISTRY-}payrocserver
    build:
      context: .
      dockerfile: Payroc.Server/Dockerfile
    ports:
     - 8080:8080
     - 8081:8081
    environment:
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://payroc.dashboard:18889
     - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    networks:
     - payroc
    depends_on:
        payroc.loadbalancer:
            condition: service_started

  payroc.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:9.2
    container_name: dashboard
    environment: 
     - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
     - 18888:18888 #dashboard
     - 4317:18889 #metrics
    networks:
     - payroc

  payroc.loadbalancer:
    image: ${DOCKER_REGISTRY-}payrocloadbalancer
    build:
      context: .
      dockerfile: Payroc.LoadBalancer/Dockerfile
    ports:
     - 9000:8080 #Kestrel
     - 5050:5050 #LoadBalancer
    networks:
     - payroc
    depends_on:
        consul:
            condition: service_started

  consul:
    image: hashicorp/consul:1.21.3
    container_name: consul
    ports:
      - "8500:8500" #HTTP API
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    networks:
      - payroc
networks:
  payroc:
    driver: bridge
    name: payroc

